### ISSUE TITLE
Add CMake to test suite

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#325]
## Description

We just switched to using Github Actions for our CI and it would be nice to add a new step that uses CMake to build the library and tests. The file can be found here:
- https://github.com/libocca/occa/blob/master/.github/workflows/build.yml

**Comment by SFrijters** [comment]
I would like to help with this, but I have no experience with GitHub Actions yet.

**Comment by dmed256** [comment]
@SFrijters Sweet!

The 2 "steps" used to compile the library + tests are:

```yml
    - name: Compile library
      run: make -j

    - name: Compile tests
      run: make -j tests
```

We would need to change it to something like

```yml
    - name: Compile library
      run: make -j
      if: ${{ !matrix.useCMake }}

    - name: Compile tests
      run: make -j tests
      if: ${{ !matrix.useCMake }}

    - name: Compile library (CMake)
      run: ???
      if: ${{ matrix.useCMake }}

    - name: Compile tests (CMake)
      run: ???
      if: ${{ matrix.useCMake }}
```

The new `useCMake` variable would come from the `matrix` definition

```yaml
      matrix:
        include:
          - name: (Ubuntu) gcc-8
            os: ubuntu-18.04
            CC: gcc-8
            CXX: g++-8
            OCCA_COVERAGE: 1
            useCMake: false             # <--- New variable useCMake defined here

          - name: (Ubuntu) CMake + gcc-8
            os: ubuntu-18.04
            CC: gcc-8
            CXX: g++-8
            OCCA_COVERAGE: 1
            useCMake: true              # <--- New variable useCMake defined here
```

**Comment by gionellef** [comment]
Hi, I'm a beginner contributor who's willing to learn from this by doing. I've looked at the issue, and... since there are CMakeLists.txt in place already and the task is supposed to just call it, is it enough to just ?

`run: cmake ./`

Is there a need to generate the cmakefiles in a separate subdirectory "build"? 

I hope I understood the requirement correctly :)

**Comment by dmed256** [comment]
@gionellef Hey, thanks for reaching out and wanting to help out!

Right now there is no CMake test in the [.github/workflows/build.yml](https://github.com/libocca/occa/blob/master/.github/workflows/build.yml) file. It would be nice to have one Github Actions job that would do instead of

```yml
    - name: Compiler info
      run: make -j info

    - name: Compile library
      run: make -j

    - name: Compile tests
      run: make -j tests

    - name: Run unit tests
      run: ./tests/run_tests

    - name: Run examples
      run: ./tests/run_examples
```

something like

```yml
    - name: Compile library
      run: <cmake command>

    - name: Compile tests
      run: <cmake command>

    - name: Run unit tests
      run: ./tests/run_tests

    - name: Run examples
      run: ./tests/run_examples
```

It might be a really simple task now that @SFrijters added `CMakeLists.txt` throughout the codebase. But I'm not too familiar with `cmake` so I was hoping to get help with this task :)

> Is there a need to generate the cmakefiles in a separate subdirectory "build"?
I think so? The few times I've used `cmake` I've built the project in a separate directory (e.g. `./build`) but up to you.
